### ISSUE TITLE
use mpris dbus interface to handle playing music

### ISSUE THREAD

**Issue by ricardomv** [Lokaltog/candybar#17]
i think mpd also has this interface so it would be good to implement it, it's also used by spotify gnome-music clementine?(not sure) and Amarok docs in http://specifications.freedesktop.org/mpris-spec/latest/

**Comment by Lokaltog** [comment]
Good idea, particularily if it works with several media players. I've been looking a bit at dbus (for libnotify support), and it looks like there's quite a bit of work involved in creating a dbus server, maybe we culd try to create some generic wrapper around dbus that could be used for several dbus services. I'm thinking something like this (pseudocode):

```
dbus_server = dbus_register('org.mpris.MediaPlayer2')
while(dbus_wait_for_event(dbus_server)) {
  event = dbus_get_event(dbus_server)
  send_data_to_statusline(event)
}
```

**Comment by Lokaltog** [comment]
As you can see in bc8325f1b9b3755f544dd39a4f4b452be50aaca9 there's a bit of boilerplate code required for listening to dbus messages, but it's not as bad as I initially thought it would be, so I don't think we'll need a wrapper (at least for now).

**Comment by ricardomv** [comment]
i have been trying to get this to work but i cant even get a property from the player in the mean time i found [this](https://github.com/brianrobles204/Music-Integration/blob/master/src/extension.js) this is really hard to do in c and really easy to do in js (any object oriented language) do you want to give it a try the interface is defined in the first 250 lines. lol, you will see, in the end the c part will only open the window but i gess we will find a way to do it in js :S

**Comment by acrisci** [comment]
Check out [playerctl](https://github.com/acrisci/playerctl) - it's a C library for MPRIS

**Comment by Lokaltog** [comment]
That looks like a huge timesaver! Great tip, thanks!

**Comment by acrisci** [comment]
I could start on implementing this without adding any dependencies. It's not that complex if you know the right way to do it.

I just wish the documentation on the widget interface was a bit better.

**Comment by Lokaltog** [comment]
That would be awesome! I apologize for the lacking docs, the reason is that I've been refactoring the widget API several times before settling on the current (probably final) API which supports JSCore.

A good place to start is to look at some of the simple widgets, e.g. the [datetime](https://github.com/Lokaltog/wkline/blob/develop/src/widgets/datetime.c) widget.

The way the widgets work is that they [call a Javascript function](https://github.com/Lokaltog/wkline/blob/develop/src/widgets/datetime.c#L22-24) whenever the state of the widget changes. The data is passed as arguments to the JS function. You need to wrap the arguments in any of the [widget_data_arg*](https://github.com/Lokaltog/wkline/blob/develop/src/widgets.h#L76-81) macros, these "cast" the data to Javascript types.

You can add add config options in the header (like which media player to use), these need to be defined as a struct in the header and registered using the [widget_init_config*](https://github.com/Lokaltog/wkline/blob/develop/src/widgets.h#L56-67) macros. These config options can then be customized by the user in config.json.

Let me know if you have any other questions, writing docs is on the todo list but I don't have an ETA on the docs yet.

**Comment by Lokaltog** [comment]
Working MPRIS widget merged into develop.
