### ISSUE TITLE
EWMH Hint reliance

### ISSUE THREAD

**Issue by bbenne10** [Lokaltog/candybar#43]
wkline currently relies upon ewmh hints to set it's role as a dock. This seems to be not quite enough, as many tiling window managers don't respect those hints. monsterwm, for instance, currently doesn't work with wkline. DWM wouldn't either (if you ripped it's built in bar out). I've not looked over the code for snapwm or dminiwm recently, but I suspect that it wouldn't work there either. 

This could be fixed by setting "override redirect" on the window, but I'm not sure how that would affect anything else. I've tried doing this locally, but I'm getting a segmetation fault that I've not yet had time to track down. I don't have the code on me now (or I'd just link to a gist-d diff), but it was in wkline.c's main() that I acquired a gdk window from the gtk window and called `gdk_set_override_redirect(gdkw, TRUE);`. Doing this led to a segmentation fault on the `gdk_set_override_redirect` line reliably (before and after any other changes to the window, so it wasn't some conflict cause by using both gtk_\* window handling and the `gdk_set_override_redirect`). 

Does anyone have any thoughts on this? I'd be happy to finish up the (probably very small) changes, if they'd be welcome.

**Comment by Lokaltog** [comment]
I agree that reliance on EWMH isn't ideal, particularily because dwm and other common WMs don't honor window hints like positioning and space reservation. I wasn't aware of the override redirect property, does this property allow us to set the window position without the WM overriding it or something?

No idea why it segfaults, but my first thought is that it might happen if you called the function before the window was drawn. Did you add it to `wk_realize_handler`?

Being able to run wkline in non-EWMH-compliant WMs would be great, it would be awesome if you'd be able to resolve this issue.

**Comment by bbenne10** [comment]
Wow. You're 100% right. Putting this in wk_realize_handler worked wonderfully. I was trying to do it in main(), because that's where the rest of the hint stuff was - but this seems to work. 

I just built and tested under dwm and it seems to work (though dwm has it's own bar...). I'll open a pull request.

**Comment by Lokaltog** [comment]
Excellent, thanks a lot!
