### ISSUE TITLE
Use a local theme by default

### ISSUE THREAD

**Issue by mrabault** [Lokaltog/candybar#67]
Hello,

I was taking a look at this project, and I noticed that the default config you provide has its theme non-local. I took a look at the default theme repo, and I understand that you perhaps don't want npm and grunt as compile-time dependencies. However, having a default config that is local is IMHO better, because:
- It is snappier because you don't depend on your network
- We don't always have Internet connectivity

Therefore, I suggest having a directory in this repo with a pregenerated version of the default theme, and copying the theme somewhere local on installation. I'd put it somewhere under /etc so that all users have access to it.

Thanks in advance for your consideration

**Comment by Lokaltog** [comment]
I agree having the theme locally would be ideal, but I want to avoid pulling in npm and a bunch of node.js packages as mandatory compile-time dependencies. I think that it should possibly be a separate waf build task instead. The task could be enabled optionally with e.g. `--compile-theme` as a configure option. Maybe the option could accept a path to a git repo like `--compile-theme="git@github.com/..."`.

Another alternative could be simply copying the theme file from the github page into a local directory when building. I want to avoid having a copy of the theme in the repo itself because it requires keeping it up to date with the theme repo, so pulling the file directly from the theme repo would be better. Maybe a submodule could work?

Anyways, I haven't had time to read up on the custom task docs for waf, but feel free to contribute a patch for this, I definitely agree that it should at least be an option to build or copy the theme locally when compiling.

**Comment by mrabault** [comment]
> Another alternative could be simply copying the theme file from the github page into a local directory when building. I want to avoid having a copy of the theme in the repo itself because it requires keeping it up to date with the theme repo, so pulling the file directly from the theme repo would be better. Maybe a submodule could work?

I agree Submodules are a pain in the ass to manage though, so what I'd suggest is having a commit hook in the default theme repo. This hook would regenerate the theme and add it to the files being committed (in a subfolder). This way, we avoid cluttering the projet repo. Furthermore, PKGBUILDs allow multiple sources. Then, we can fetch the code itself, then the theme, and move the theme because then we don't have npm and all this stuff as build dependencies. What do you think of that ? I can't see any drawbacks to this, but there must be some.

(I'm aware of the fact that it's quite awkward, but I still think that it's better than having too much build dependencies and/or an Internet connectivity dependency)
