### ISSUE TITLE
Can't update widget data from callback function.

### ISSUE THREAD

**Issue by alspore** [Lokaltog/candybar#68]
It appears that the `widget_data_callback` macro crashes whenever it's run from a callback function set with `g_signal_connect_closure`.  This makes it a bit more difficult to  optimize receiving data through the "workspace" signal provided in the `i3ipc-glib` library for the temporary i3wm desktops widget replacement.  I think I'm a bit in over my head.

[Here's a link to the specific code I'm having problems with at around line 42](https://github.com/5paceManSpiff/candybar/blob/i3ipc-glib/src/widgets/desktops_i3.c).  The callback is set through the convenience function `i3ipc_connection_on` which subscribes to signals through i3.  [The code for this function can be found here at around line 916](https://github.com/5paceManSpiff/candybar/blob/i3ipc-glib/src/widgets/desktops_i3.c).

**Comment by Lokaltog** [comment]
The `widget_data_callback` macro runs `web_view_callback()` with the callback data the next loop in the main loop with `g_idle_add()`. Maybe glib doesn't like nested callbacks? If you're certain that your callback runs from the main thread you can call `web_view_callback` directly instead of asking glib to run it in the main loop.

**Comment by alspore** [comment]
Thanks, I've been able to run `web_vew_callback directly`.
