### ISSUE TITLE
wscript looks for playerctl version 1.0, which isn't found even if playerctl is installed

### ISSUE THREAD

**Issue by Jwpe** [Lokaltog/candybar#77]
It appears that the `mpris` widget is [trying to rely](https://github.com/Lokaltog/candybar/blob/develop/wscript#L73) on a version of `playerctl` that doesn't exist: 

```
ctx.check_cfg(package='playerctl-1.0', uselib_store='PLAYERCTL', args=['--cflags', '--libs'], mandatory=False)
```

As far as I know, the [latest version](https://github.com/acrisci/playerctl/releases/tag/v0.2.1) is `0.2.1`. I have `0.2.0` installed from the `.deb`. I tried changing the `package` in the line above to `playerctl` and `playerctl-0.2.0`, but the `waf` script still doesn't recognise it.

Am I just getting the configuration wrong?

**Comment by Lokaltog** [comment]
I thought about the same when I merged it, but playerctl provides `/usr/lib/pkgconfig/playerctl-1.0.pc` on arch so that's why the version is different (waf uses pkg-config to get the include flags). There may be something wrong with the .deb package, e.g. the .pc files may be installed in the wrong location. You can check which (if any) pkg-config files are installed by running `dpkg -L playerctl | grep "\.pc"`.

Closing this as it's not a candybar issue, if you can't resolve it you should report it to @acrisci.

**Comment by acrisci** [comment]
Yeah 0.2.1 is required for building with playerctl. I'll make a debian package and post it to the latest release in a bit.

**Comment by Jwpe** [comment]
@Lokaltog thanks, that makes sense. @acrisci cool!
