### ISSUE TITLE
Window_title keeps displaying window title after workspace change (i3 wm)

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#78]
I'm not sure if this is a bug or intended behaviour, but here it goes. Here's an example of my problem in case it's not clear:

\- Only have one workspace, no gui applications open
- Open Firefox, window_title in candybar is updated to reflect FF title
- Switch to new blank workspace in i3, however window_title still shows FF title

Window_title should not output anything on a blank workspace in my opinion.

**Comment by alspore** [comment]
As far as I understand, this is due to the differences in the way X and i3 handle focused windows.  I could throw together a `window_title` i3 replacement if you'd like, though I feel like that may be overkill.

**Comment by ghost** [comment]
That would be great. However, why do you think it may be overkill?

**Comment by alspore** [comment]
At first I thought requiring an alternative plugin to fix a minor bug seemed a bit much for the average user, though on second thought that should be irrelevant as long as it's optional.  So never mind.

**Comment by Lokaltog** [comment]
This is most likely due to i3's lack of EWMH support, but they're working on it. Both the default desktops list and window title widgets depend on EWMH properties and X events sent by the window manager, but i3 doesn't support desktop change notifications so candybar has no way of knowing if the desktops have been changed, this is why the window title fails to update when changing desktops, but works otherwise.

I personally don't think this is an issue that requires a separate widget as it's a minor bug that's being worked on by the i3 devs, but I'll merge a separate `window_title_i3` widget if anyone wants to implement it.

**Comment by acrisci** [comment]
I think this should be moved to the [i3wm bug tracker](http://bugs.i3wm.org) because it is definitely an i3 issue.

**Comment by acrisci** [comment]
I'm fixing this now in i3

**Comment by Lokaltog** [comment]
Excellent, let me know when it's ready in i3 and I'll update the docs regarding the i3 widgets.

**Comment by acrisci** [comment]
Fixed in the development version of i3

**Comment by ghost** [comment]
i3 4.8.1 stable was pushed to arch's repos and the issue is fixed. Closing.
