### ISSUE TITLE
WARNING timed out waiting for widget battery to exit

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#88]
Whenever I start up candybar these errors are printed

```
[02:52:18] ERROR dbus error: The name org.freedesktop.UPower was not provided by any .service files
[02:52:18] ERROR dbus: invalid battery (battery.c)

```

This is to be expected, as I don't have UPower installed. However, if I attempt to exit the program using ctrl+c there is a 1 second delay and then this error is printed

```
WARNING timed out waiting for widget battery to exit
```

I would think that candybar wouldn't load the the battery module in the first place if an error like the initial dbus ones were printed. I remember you stating that you didn't have a lot of sanity checking code in place yet, so I assume that's still the case.

**Comment by Lokaltog** [comment]
It should exit the widget at startup, and the warning should probably be a info message instead. The warning is caused by the main thread signalling the child thread to shut down with a one second timeout, but since the child thread is already terminated it can't reply so it's cancelled/force killed by the main thread after the timeout. I'm not sure how to resolve this, but it's not a bug, it's expected behavior but could probably be handled better.

I honestly don't know if it's safe to just kill the child threads right away, or if they have to free resources before exiting, but from what I've read it's pretty important to manage memory and resources in C which is why I've added the feature for child threads to exit gracefully and cleanup any resources.
