### ISSUE TITLE
candybar doesn't seem track the mouse exiting its window vertically

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#89]
Lets say that candybar is in its "idle" state, where all the expandable windows are currently compacted and the mouse cursor is not on the bar's window. If I move my mouse over to one of the expandable applets, then as expected it will expand. However, when I move my mouse out of candybar's window vertically (so that the last pixel my cursor was on while inside candybar's window was inside the widgets space), the widget remains open, but my cursor is no longer inside candybar's area.

Presumably, checking if a cursor is overhead is only done for candybar's window because if I mouse away from a widget horizontally, e.g. still in candybar's window, then the widget properly compacts. This is probably going to seem convoluted as far as bug reports go, but I want to be as clear as possible the first time around.

**Comment by Lokaltog** [comment]
I know what you mean, this issue is bugging me as well. The problem is that the CSS :hover effect doesn't receive the "cursor left the element" event as the element is at the edge of the web view and the web view doesn't handle cursor events when the cursor has left it. A way to resolve this is to trigger the hide effect with javascript after a timeout of e.g. 1 second after the last cursor event.

I'm planning on doing a refactor and redesign of the default theme later (add a generic widget type and handle jscore requests), and I'm planning on solving this issue when I do that.
